### ISSUE TITLE
exec: sommelier: Permission Denied

### ISSUE THREAD

**Issue by jackadamson** [Coffeeinator/leagueoflinux#1]
Latest build seems to have broke leagueoflinux as the file:
/snap/leagueoflinux/10/bin/sommelier 
Not has permissions set to 0644
Error message:
`/snap/leagueoflinux/10/command-leagueoflinux.wrapper: 6: exec: /snap/leagueoflinux/10/bin/sommelier: Permission denied`

**Comment by jackadamson** [comment]
Running fresh Ubuntu 18.04
Installed with `snap install leagueoflinux --edge --devmode`

**Comment by jackadamson** [comment]
Able to workaround issue doing the following: 
```sudo mkdir /tmp/leaguesnapfs
sudo unsquashfs -f -d /tmp/leaguesnapfs /var/lib/snapd/snaps/leagueoflinux_10.snap
sudo chmod +x /tmp/leaguesnapfs/bin/sommelier /tmp/leaguesnapfs/bin/winetricks /tmp/leaguesnapfs/bin/zenity
sudo mksquashfs /tmp/leaguesnapfs /tmp/newleaguesquashfs
sudo chmod 600 /tmp/newleaguesquashfs
sudo umount /snap/leagueoflinux/10
sudo mv /tmp/newleaguesquashfs /var/lib/snapd/snaps/leagueoflinux_10.snap
sudo reboot
```
The 10 is the revision number so that will change, also fairly certain you can restart some service or remount instead of reboot, but reboot is a bit safer. 
League now works like a charm and it's only my ranked team mates that are broken.
Good job on putting this project together!

**Comment by Coffeeinator** [comment]
Thanks for solution but new version (16) is working out of the box. The package build software form snapstore was a culprit. I need to push packages to store personally.
