### ISSUE TITLE
Error launching game after champion select

### ISSUE THREAD

**Issue by freefri** [Coffeeinator/leagueoflinux#2]
Since League of Legends 8.12 (summer 2018) Riot release an anti-cheat update which was causing the game to crash on launch (see League of Legends boards: Game client anti-cheat known issues and fixes) Some users are reporting the game should be working again, but I'm still facing problems going into the game, right after champion select (when the 5 champion splash images should be displayed while loading):

> 0247:fixme:seh:RtlSetUnhandledExceptionFilter (0x1029bd20) stub!
Unable to update the static FcBlanks: 0xfffb
0247:fixme:virtual:NtQueryVirtualMemory (process=0xffffffff,addr=(nil)) Unimplemented information class: MemoryWorkingSetExInformation
0247:fixme:ntdll:NtQuerySystemInformation (0x00000039,0x47a0020,0x00100000,0x33d288) stub

![screenshot from 2018-10-02 07-49-54](https://user-images.githubusercontent.com/2754631/46331352-ce26d900-c617-11e8-9611-386eda01013d.png)

Using Nvidia GTX 560 Ti Driver version 375.66

`snap version`
snap 2.35
snapd 2.35
series 16
debian 9
kernel 4.9.0-3-amd64

**Comment by Coffeeinator** [comment]
Type leagueoflinux.winecfg in terminal and change windows version to windows 10 click OK and Apply. Type again leagueoflinux.winecfg and change back windows version to xp. It is working for you?

**Comment by freefri** [comment]
I've made a clean install of Ubuntu 18.04 with the latest Nvidia Driver 390.48 for my GTX 560 Ti. And with the old install of the snap (I've kept my old /home directory and the /home/user/snap directory too) it worked without any problems.

I think the problem was related with the Nvidia drivers in Debian 9 (that's why the error message `failed to load driver: swrast` appeared in the console, not with this project (league snap).

**Comment by Coffeeinator** [comment]
Could you tell me which snap revision do you use for testing?
BTW: Nvidia drivers could be a really pain in the ass. It's recommended to use only drivers from Ubuntu Additional Software settings/Tab or downloaded directly from Nvidia website.

**Comment by freefri** [comment]
Both times I was using the latest snap from --edge
